#! /bin/bash

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

# Set up the environment
INPUT_DIR=`jq -r '.input_dir' config.json`
OUTPUT_DIR=`jq -r '.output_dir' config.json`
N_PROCS=`jq -r '.n_procs' config.json`
PLACEMENT=`jq -r '.placement' config.json`
SKIP_BIDS_VALIDATOR=`jq -r '.skip_bids_validator' config.json`
PARTICIPANT_LABEL=`jq -r '.participant_label' config.json`


timit singularity exec -e \
    -B ${FREESURFER_LICENSE}:/opt/freesurfer/license.txt \
    "docker://openneuropet/petdeface:latest" \
    petdeface \
    ${INPUT_DIR} \
    --output_dir ${OUTPUT_DIR} \
    --n_procs ${N_PROCS} \
    --placement ${PLACEMENT} \
    --n_procs ${N_PROCS} \
    --skip_bids_validator ${SKIP_BIDS_VALIDATOR} \
    --participant_label ${PARTICIPANT_LABEL} 
