name: petdeface
on:
  workflow_call:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  test_petdeface:
    runs-on: ubuntu-latest
    name: Test petdeface
    strategy:
      matrix:
        toolchain: [uv, pip]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies (UV)
        if: matrix.toolchain == 'uv'
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          uv sync --dev
      - name: Install dependencies (pip)
        if: matrix.toolchain == 'pip'
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run All Tests (UV)
        if: matrix.toolchain == 'uv'
        run: uv run make testall
      - name: Run All Tests (pip)
        if: matrix.toolchain == 'pip'
        run: make testall