name: petdeface
on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  PreviewDocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
          cache: poetry
      - run: poetry install
      - name: Preview Docs
        uses: readthedocs/actions/preview@v1